-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "projects" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "target_domain" TEXT NOT NULL DEFAULT '',
    "subdomain_list" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "verify_domain_ownership" BOOLEAN NOT NULL DEFAULT false,
    "ownership_token" TEXT NOT NULL DEFAULT 'your-secret-token-here',
    "ownership_txt_prefix" TEXT NOT NULL DEFAULT '_redamon-verify',
    "scan_modules" TEXT[] DEFAULT ARRAY['domain_discovery', 'port_scan', 'http_probe', 'resource_enum', 'vuln_scan']::TEXT[],
    "update_graph_db" BOOLEAN NOT NULL DEFAULT true,
    "use_tor_for_recon" BOOLEAN NOT NULL DEFAULT false,
    "use_bruteforce_for_subdomains" BOOLEAN NOT NULL DEFAULT true,
    "whois_max_retries" INTEGER NOT NULL DEFAULT 6,
    "dns_max_retries" INTEGER NOT NULL DEFAULT 3,
    "github_access_token" TEXT NOT NULL DEFAULT '',
    "github_target_org" TEXT NOT NULL DEFAULT '',
    "github_scan_members" BOOLEAN NOT NULL DEFAULT false,
    "github_scan_gists" BOOLEAN NOT NULL DEFAULT true,
    "github_scan_commits" BOOLEAN NOT NULL DEFAULT true,
    "github_max_commits" INTEGER NOT NULL DEFAULT 100,
    "github_output_json" BOOLEAN NOT NULL DEFAULT true,
    "naabu_docker_image" TEXT NOT NULL DEFAULT 'projectdiscovery/naabu:latest',
    "naabu_top_ports" TEXT NOT NULL DEFAULT '1000',
    "naabu_custom_ports" TEXT NOT NULL DEFAULT '',
    "naabu_rate_limit" INTEGER NOT NULL DEFAULT 1000,
    "naabu_threads" INTEGER NOT NULL DEFAULT 25,
    "naabu_timeout" INTEGER NOT NULL DEFAULT 10000,
    "naabu_retries" INTEGER NOT NULL DEFAULT 1,
    "naabu_scan_type" TEXT NOT NULL DEFAULT 's',
    "naabu_exclude_cdn" BOOLEAN NOT NULL DEFAULT false,
    "naabu_display_cdn" BOOLEAN NOT NULL DEFAULT true,
    "naabu_skip_host_discovery" BOOLEAN NOT NULL DEFAULT true,
    "naabu_verify_ports" BOOLEAN NOT NULL DEFAULT true,
    "naabu_passive_mode" BOOLEAN NOT NULL DEFAULT false,
    "httpx_docker_image" TEXT NOT NULL DEFAULT 'projectdiscovery/httpx:latest',
    "httpx_threads" INTEGER NOT NULL DEFAULT 50,
    "httpx_timeout" INTEGER NOT NULL DEFAULT 10,
    "httpx_retries" INTEGER NOT NULL DEFAULT 2,
    "httpx_rate_limit" INTEGER NOT NULL DEFAULT 50,
    "httpx_follow_redirects" BOOLEAN NOT NULL DEFAULT true,
    "httpx_max_redirects" INTEGER NOT NULL DEFAULT 10,
    "httpx_probe_status_code" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_content_length" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_content_type" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_title" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_server" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_response_time" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_word_count" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_line_count" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_tech_detect" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_ip" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_cname" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_tls_info" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_tls_grab" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_favicon" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_jarm" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_hash" TEXT NOT NULL DEFAULT 'sha256',
    "httpx_include_response" BOOLEAN NOT NULL DEFAULT true,
    "httpx_include_response_headers" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_asn" BOOLEAN NOT NULL DEFAULT true,
    "httpx_probe_cdn" BOOLEAN NOT NULL DEFAULT true,
    "httpx_paths" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "httpx_custom_headers" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "httpx_match_codes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "httpx_filter_codes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "wappalyzer_enabled" BOOLEAN NOT NULL DEFAULT true,
    "wappalyzer_min_confidence" INTEGER NOT NULL DEFAULT 50,
    "wappalyzer_require_html" BOOLEAN NOT NULL DEFAULT true,
    "wappalyzer_auto_update" BOOLEAN NOT NULL DEFAULT true,
    "wappalyzer_npm_version" TEXT NOT NULL DEFAULT '6.10.56',
    "wappalyzer_cache_ttl_hours" INTEGER NOT NULL DEFAULT 24,
    "banner_grab_enabled" BOOLEAN NOT NULL DEFAULT true,
    "banner_grab_timeout" INTEGER NOT NULL DEFAULT 5,
    "banner_grab_threads" INTEGER NOT NULL DEFAULT 20,
    "banner_grab_max_length" INTEGER NOT NULL DEFAULT 500,
    "nuclei_severity" TEXT[] DEFAULT ARRAY['critical', 'high', 'medium', 'low']::TEXT[],
    "nuclei_templates" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "nuclei_exclude_templates" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "nuclei_custom_templates" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "nuclei_rate_limit" INTEGER NOT NULL DEFAULT 100,
    "nuclei_bulk_size" INTEGER NOT NULL DEFAULT 25,
    "nuclei_concurrency" INTEGER NOT NULL DEFAULT 25,
    "nuclei_timeout" INTEGER NOT NULL DEFAULT 10,
    "nuclei_retries" INTEGER NOT NULL DEFAULT 1,
    "nuclei_tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "nuclei_exclude_tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "nuclei_dast_mode" BOOLEAN NOT NULL DEFAULT true,
    "nuclei_auto_update_templates" BOOLEAN NOT NULL DEFAULT true,
    "nuclei_new_templates_only" BOOLEAN NOT NULL DEFAULT false,
    "nuclei_headless" BOOLEAN NOT NULL DEFAULT false,
    "nuclei_system_resolvers" BOOLEAN NOT NULL DEFAULT true,
    "nuclei_follow_redirects" BOOLEAN NOT NULL DEFAULT true,
    "nuclei_max_redirects" INTEGER NOT NULL DEFAULT 10,
    "nuclei_scan_all_ips" BOOLEAN NOT NULL DEFAULT false,
    "nuclei_interactsh" BOOLEAN NOT NULL DEFAULT true,
    "nuclei_docker_image" TEXT NOT NULL DEFAULT 'projectdiscovery/nuclei:latest',
    "katana_docker_image" TEXT NOT NULL DEFAULT 'projectdiscovery/katana:latest',
    "katana_depth" INTEGER NOT NULL DEFAULT 3,
    "katana_max_urls" INTEGER NOT NULL DEFAULT 500,
    "katana_rate_limit" INTEGER NOT NULL DEFAULT 50,
    "katana_timeout" INTEGER NOT NULL DEFAULT 900,
    "katana_js_crawl" BOOLEAN NOT NULL DEFAULT true,
    "katana_params_only" BOOLEAN NOT NULL DEFAULT false,
    "katana_exclude_patterns" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "katana_scope" TEXT NOT NULL DEFAULT 'dn',
    "katana_custom_headers" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "gau_enabled" BOOLEAN NOT NULL DEFAULT true,
    "gau_docker_image" TEXT NOT NULL DEFAULT 'sxcurity/gau:latest',
    "gau_providers" TEXT[] DEFAULT ARRAY['wayback', 'commoncrawl', 'otx', 'urlscan']::TEXT[],
    "gau_max_urls" INTEGER NOT NULL DEFAULT 1000,
    "gau_timeout" INTEGER NOT NULL DEFAULT 60,
    "gau_threads" INTEGER NOT NULL DEFAULT 5,
    "gau_blacklist_extensions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "gau_year_range" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "gau_verbose" BOOLEAN NOT NULL DEFAULT false,
    "gau_verify_urls" BOOLEAN NOT NULL DEFAULT true,
    "gau_verify_docker_image" TEXT NOT NULL DEFAULT 'projectdiscovery/httpx:latest',
    "gau_verify_timeout" INTEGER NOT NULL DEFAULT 5,
    "gau_verify_rate_limit" INTEGER NOT NULL DEFAULT 100,
    "gau_verify_threads" INTEGER NOT NULL DEFAULT 50,
    "gau_verify_accept_status" INTEGER[] DEFAULT ARRAY[200, 201, 301, 302, 307, 308, 401, 403]::INTEGER[],
    "gau_detect_methods" BOOLEAN NOT NULL DEFAULT true,
    "gau_method_detect_timeout" INTEGER NOT NULL DEFAULT 5,
    "gau_method_detect_rate_limit" INTEGER NOT NULL DEFAULT 50,
    "gau_method_detect_threads" INTEGER NOT NULL DEFAULT 25,
    "gau_filter_dead_endpoints" BOOLEAN NOT NULL DEFAULT true,
    "kiterunner_enabled" BOOLEAN NOT NULL DEFAULT true,
    "kiterunner_wordlists" TEXT[] DEFAULT ARRAY['apiroutes-251227', 'directories-251227', 'raft-large-directories']::TEXT[],
    "kiterunner_rate_limit" INTEGER NOT NULL DEFAULT 100,
    "kiterunner_connections" INTEGER NOT NULL DEFAULT 100,
    "kiterunner_timeout" INTEGER NOT NULL DEFAULT 10,
    "kiterunner_scan_timeout" INTEGER NOT NULL DEFAULT 1000,
    "kiterunner_threads" INTEGER NOT NULL DEFAULT 50,
    "kiterunner_ignore_status" INTEGER[] DEFAULT ARRAY[404, 400, 502, 503]::INTEGER[],
    "kiterunner_min_content_length" INTEGER NOT NULL DEFAULT 0,
    "kiterunner_match_status" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
    "kiterunner_headers" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "kiterunner_detect_methods" BOOLEAN NOT NULL DEFAULT true,
    "kiterunner_method_detection_mode" TEXT NOT NULL DEFAULT 'bruteforce',
    "kiterunner_bruteforce_methods" TEXT[] DEFAULT ARRAY['POST', 'PUT', 'DELETE', 'PATCH']::TEXT[],
    "kiterunner_method_detect_timeout" INTEGER NOT NULL DEFAULT 5,
    "kiterunner_method_detect_rate_limit" INTEGER NOT NULL DEFAULT 50,
    "kiterunner_method_detect_threads" INTEGER NOT NULL DEFAULT 25,
    "cve_lookup_enabled" BOOLEAN NOT NULL DEFAULT true,
    "cve_lookup_source" TEXT NOT NULL DEFAULT 'nvd',
    "cve_lookup_max_cves" INTEGER NOT NULL DEFAULT 20,
    "cve_lookup_min_cvss" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "vulners_api_key" TEXT NOT NULL DEFAULT '',
    "nvd_api_key" TEXT NOT NULL DEFAULT '',
    "mitre_auto_update_db" BOOLEAN NOT NULL DEFAULT true,
    "mitre_include_cwe" BOOLEAN NOT NULL DEFAULT true,
    "mitre_include_capec" BOOLEAN NOT NULL DEFAULT true,
    "mitre_enrich_recon" BOOLEAN NOT NULL DEFAULT true,
    "mitre_enrich_gvm" BOOLEAN NOT NULL DEFAULT true,
    "mitre_cache_ttl_hours" INTEGER NOT NULL DEFAULT 24,
    "security_check_enabled" BOOLEAN NOT NULL DEFAULT true,
    "security_check_direct_ip_http" BOOLEAN NOT NULL DEFAULT true,
    "security_check_direct_ip_https" BOOLEAN NOT NULL DEFAULT true,
    "security_check_ip_api_exposed" BOOLEAN NOT NULL DEFAULT true,
    "security_check_waf_bypass" BOOLEAN NOT NULL DEFAULT true,
    "security_check_tls_expiring_soon" BOOLEAN NOT NULL DEFAULT true,
    "security_check_tls_expiry_days" INTEGER NOT NULL DEFAULT 30,
    "security_check_missing_referrer_policy" BOOLEAN NOT NULL DEFAULT true,
    "security_check_missing_permissions_policy" BOOLEAN NOT NULL DEFAULT true,
    "security_check_missing_coop" BOOLEAN NOT NULL DEFAULT true,
    "security_check_missing_corp" BOOLEAN NOT NULL DEFAULT true,
    "security_check_missing_coep" BOOLEAN NOT NULL DEFAULT true,
    "security_check_cache_control_missing" BOOLEAN NOT NULL DEFAULT true,
    "security_check_login_no_https" BOOLEAN NOT NULL DEFAULT true,
    "security_check_session_no_secure" BOOLEAN NOT NULL DEFAULT true,
    "security_check_session_no_httponly" BOOLEAN NOT NULL DEFAULT true,
    "security_check_basic_auth_no_tls" BOOLEAN NOT NULL DEFAULT true,
    "security_check_spf_missing" BOOLEAN NOT NULL DEFAULT true,
    "security_check_dmarc_missing" BOOLEAN NOT NULL DEFAULT true,
    "security_check_dnssec_missing" BOOLEAN NOT NULL DEFAULT true,
    "security_check_zone_transfer" BOOLEAN NOT NULL DEFAULT true,
    "security_check_admin_port_exposed" BOOLEAN NOT NULL DEFAULT true,
    "security_check_database_exposed" BOOLEAN NOT NULL DEFAULT true,
    "security_check_redis_no_auth" BOOLEAN NOT NULL DEFAULT true,
    "security_check_kubernetes_api_exposed" BOOLEAN NOT NULL DEFAULT true,
    "security_check_smtp_open_relay" BOOLEAN NOT NULL DEFAULT true,
    "security_check_csp_unsafe_inline" BOOLEAN NOT NULL DEFAULT true,
    "security_check_insecure_form_action" BOOLEAN NOT NULL DEFAULT true,
    "security_check_no_rate_limiting" BOOLEAN NOT NULL DEFAULT true,
    "security_check_timeout" INTEGER NOT NULL DEFAULT 10,
    "security_check_max_workers" INTEGER NOT NULL DEFAULT 10,

    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
